[loggers]
keys=root

[handlers]
keys=rootHandler

[formatters]
keys=rootFormatter

[logger_root]
level=DEBUG
handlers=rootHandler

[handler_rootHandler]
class=FileHandler
level=INFO
formatter=rootFormatter
args=('app.log',)

[formatter_rootFormatter]
format= %(asctime)s - %(process)s - %(levelname)s - %(message)s